### ISSUE TITLE
New name

### ISSUE THREAD

**Issue by davelab6** [Kelvinsong/swiftday#1]
The github description says, 

> A yet-unnamed typeface, now resurfacing above ground

So I thought I'd open an issue to discuss new names. 

Anything with Swift in the name is not a good choice, because of Gerard Unger's very famous Swift typeface:

https://www.google.com/search?q=swift+font+unger&tbm=isch

http://namecheck.fontdata.com is a useful web app for checking for existing font names.

**Comment by tayloraswift** [comment]
Ya Ik, coming up with a permanent name is important. Having trouble thinking of a good permanent name though…

**Comment by davelab6** [comment]
You can rename the repo, which will set up redirects from the old URLs, at https://github.com/Kelvinsong/swiftday/settings

**Comment by adrientetar** [comment]
Swift vs Swiftday is considered too close?

**Comment by tayloraswift** [comment]
not necessarily but it isn’t a “real” name at any rate

**Comment by davelab6** [comment]
Yes, there is USA case law on trademarks for typefaces that the first 3
letters the same is OK

Thus monotype neé Ascender did Arimo, Cousine and Tinos metric compatible
fonts with Arial, Courier, Times New Roman

**Comment by davelab6** [comment]
Noctilucenta is a great name :) Github has redirection features so that if you can rename the repo in https://github.com/kelvin13/swiftday/settings from swiftday to noctilucenta it will set up all needed redirections on the site

**Comment by tayloraswift** [comment]
done
