### ISSUE TITLE
LICENSE

### ISSUE THREAD

**Issue by davelab6** [Kelvinsong/swiftday#2]
Please apply the SIL Open Font License to this project, the leading libre license for fonts :)

Here is a file you can drop into the repo to do so: https://gist.github.com/davelab6/4c52bd187803fd50a88a

**Comment by tayloraswift** [comment]
Does SILOFL include a share alike thing? Kinda want to avoid the nightmare that happened to Charter

**Comment by davelab6** [comment]
Yes, see https://gist.github.com/davelab6/4c52bd187803fd50a88a#file-ofl-txt-L57-L58

**Comment by tayloraswift** [comment]
done!

**Comment by tayloraswift** [comment]
uhh how do I close a github issue

**Comment by davelab6** [comment]
You should see the close button at the end:

![screen shot 2015-05-01 at 1 28 56 pm](https://cloud.githubusercontent.com/assets/261579/7434129/01e93f62-f006-11e4-9d41-0ccb1c3936a7.png)

But its a good idea to let issue openers close their own issues, so I'll do that :)
